#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += s5k5e8yxmipiraw_Sensor.o

KBUILD_CFLAGS += -Wno-error=unused-function -Wno-error=implicit-function-declaration -Wno-error=unused-variable -Wno-error=strict-prototypes
